### ISSUE TITLE
Pagination Issue - Page 2 gets 'Darn It.  Nothing Found'

### ISSUE THREAD

**Issue by vothsco** [boonebgorges/buddypress-docs-wiki#20]
CBOX member Helen White reports an issue that when more than one page of wiki posts are listed,   pagination message indicates correctly that there is an additional page, but when clicking on page "2", 
she gets the "Darn It.  Nothing Found." message.

Here is a link to the wiki page where it is happening:
http://clientdevelopment2.co.uk/chgn-final/wiki/ 

Here is a link to the forum thread:
http://commonsinabox.org/groups/help-support/forum/topic/wiki-pagination-issue/

**Comment by brooks1man** [comment]
I am also experiencing this problem on both versions 1.0.7 and 1.0.8 of buddypress-docs-wiki. It looks like this pagination issue also extends to wiki tags - if you have more than one page of a certain tag when clicking on any subsequent pages the first page is just reloaded.

**Comment by boonebgorges** [comment]
Thanks for the report, and sorry that this got buried.

91b3361 should fix the issue. You can wait until 1.0.9, or you can manually apply the changeset to your installation. If you do the latter, be sure to resave your settings at Dashboard > Settings > Permalinks for the changes to take effect.

**Comment by brooks1man** [comment]
For me this is only a partial fix. It no longer displays the "Darn it.. Nothing found" page but no matter what page number I click on it only displays the first page of results.

**Comment by boonebgorges** [comment]
What URLs do you see when you are on subsequent pages? What version of BuddyPress Docs are you using?

**Comment by brooks1man** [comment]
The landing page and the next two pages are:
https://intranet.springfield.gsu.edu/wiki/
https://intranet.springfield.gsu.edu/wiki/page/2/
https://intranet.springfield.gsu.edu/wiki/page/3/

I'm on BP Docs Wiki version 1.0.8 and BP Docs version 1.8.5. I didn't update the entire plugin for the fix, I just changed the code for the commit 91b3361.

**Comment by boonebgorges** [comment]
Thanks. This could be related to 
https://github.com/boonebgorges/buddypress-docs/issues/438. I recommend 
that you update your BuddyPress Docs to the latest 1.8.x branch 
https://github.com/boonebgorges/buddypress-docs/tree/1.8.x or manually 
apply this changeset 
https://github.com/boonebgorges/buddypress-docs/commit/99cb2dee79689f579780aa8d0e514ea14694fda4 
to see if it fixes it.

**Comment by brooks1man** [comment]
I applied the changes from the https://github.com/boonebgorges/buddypress-docs/commit/99cb2dee79689f579780aa8d0e514ea14694fda4 commit and refreshed the permalink structure and I still have the same results. The URL updates to the correct looking structure but the content is always the same from the first page. The pagination never updates and always looks the same:
![image](https://cloud.githubusercontent.com/assets/4126870/6928045/56c855e0-d7bf-11e4-8e0d-c555984640b2.png)

**Comment by boonebgorges** [comment]
Thanks for giving it a test. I'll try to look into this. In the 
meantime, if you are able to do any sort of debugging (presumably this 
is an issue where the improper 'page' param is being passed to the 
query), please do report any results back here.

**Comment by brooks1man** [comment]
Sounds good, I'll take more in depth look at it and let you know if I find anything.
